### ISSUE TITLE
Query re: Plugins

### ISSUE THREAD

**Issue by iandarbeynhiu** [hassio-addons/addon-plex#235]
# Problem/Motivation

Unable to locate plugins directory from HASS.io file browser. Can see within Plex add on if I try to add media.
As a result unable to add plugins / bundles to the folder for use in the plex add on.

## Expected behavior

Able to add plugins to designated plugin folder.

## Actual behavior

Can't find folder or any addon config data outside of addon.

## Proposed changes

map a HASS.io accessable folder for use as the plugins folder?

**Comment by frenck** [comment]
This add-on used to have plugin support back in the day (including WebTools); this was later removed due to issues. The request has since then never came up again, so for that reason I'm not planning on re-introducing the ability.

Unfortunately, therefore, I have to say: If you need this functionality, this add-on isn't for you.

../Frenck

**Comment by BeachyHeadCode** [comment]
@frenck That is survivors bias. Many individuals want plugins and are not speaking up like me. I've been monitoring this addon for years to see if it would finally add this.

@iandarbeynhiu You can use this addon here https://github.com/alexbelgium/hassio-addons to have plex plugins supported server. There are no issues I've had on it over the past 2 years. It works without the need to inject your own docker container and uses the native HA addon manager.
